return {
    PLUGIN_ROOT = "plugins/readingfolio.koplugin/",

    BG_SETTING = "reading_folio_screensaver_background",
    BG_IMAGE_MODE_SETTING = "reading_folio_bg_image_mode",
    CONTENT_MODE_SETTING = "reading_folio_content_mode",
    COVER_SCALE_SETTING = "reading_folio_cover_scale",
    STYLE_SETTING = "reading_folio_style",
    LANGUAGE_SETTING = "reading_folio_language",
    PREVIOUS_SCREENSAVER_TYPE = "reading_folio_previous_screensaver_type",
    CARD_RATIO_MODE = "reading_folio_card_ratio_mode",
    CARD_RATIO_CUSTOM = "reading_folio_card_ratio_custom",
    BORDER = "reading_folio_card_border",
    CARD_BG = "reading_folio_card_bg",
    SHADOW = "reading_folio_card_shadow",
    FONT_DELTA_BIG = "reading_folio_font_delta_big",
    FONT_DELTA_MID = "reading_folio_font_delta_mid",
    FONT_DELTA_SMALL = "reading_folio_font_delta_small",

    SHOW_TITLE = "reading_folio_show_title",
    SHOW_AUTHOR = "reading_folio_show_author",
    SHOW_COVER = "reading_folio_show_cover",
    SHOW_CHAPTER = "reading_folio_show_chapter",
    SHOW_PAGE_NUMBER = "reading_folio_show_page_number",
    SHOW_PERCENTAGE = "reading_folio_show_percentage",
    SHOW_PROGRESS_BAR = "reading_folio_show_progress_bar",
    SHOW_CHAPTER_TIME_LEFT = "reading_folio_show_chapter_time_left",
    SHOW_BOOK_TIME_LEFT = "reading_folio_show_book_time_left",
    SHOW_TOTAL_TIME = "reading_folio_show_total_time",
    SHOW_TODAY_TIME = "reading_folio_show_today_time",
    SHOW_BATTERY = "reading_folio_show_battery",
    SHOW_CLOCK = "reading_folio_show_clock",
    SHOW_HIGHLIGHTS = "reading_folio_show_highlights",
    SHOW_CUSTOM_MESSAGE = "reading_folio_show_custom_message",

    MAX_HIGHLIGHT_SIZE = 500,
    HIDE_COVER_FOR_LARGE_HIGHLIGHTS = 300,

    CONTENT_MODE_READING_FOLIO = "reading_folio",
    CONTENT_MODE_HIGHLIGHT_PROGRESS = "highlight_progress",
    CONTENT_MODE_RANDOM = "random",

    DEFAULT_STYLE = "swiss",
}
